---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
      - "vars/{{ansible_os_family}}.yml"
      - 'vars/main.yml'
      skip: 'true'
  tags:
    - config
    - nginx

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'template create vhost'
  template:
    src: "{{file_src_vhost}}"
    dest: "{{file_path_vhosts_d}}/{{item.name}}-{{(item.port|int)}}.conf"
    mode: "{{file_mode_vhost}}"
    owner: "{{file_owner_vhost}}"
    group: "{{file_group_vhost}}"
  with_items: "{{nginx_vhost}}"
  notify:
    - 'command check nginx'
    - 'service reload nginx'
  when: not (item.state is match('false|no|remove'))
  tags:
    - config
    - nginx

- name: 'file remove vhost'
  file:
    state: 'absent'
    path: "{{file_path_vhosts_d}}/{{item.name}}-{{(item.port|int)}}.conf"
  with_items: "{{nginx_vhost}}"
  notify:
    - 'command check nginx'
    - 'service reload nginx'
  when: (item.state is match('false|no|remove'))
  tags:
    - config
    - nginx
