---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'
  tags:
    - install
    - nginx

#-------------------------------------------------------------------------------
# PACKAGING
#-------------------------------------------------------------------------------

- name: 'package install nginx'
  package:
    state: 'present'
    name: "{{package_name_nginx}}"
  tags:
    - install
    - nginx

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'file create log.dir'
  file:
    state: 'directory'
    path: "{{file_dst_log_dir}}"
    mode: "{{file_mode_log_dir}}"
    owner: "{{file_owner_log_dir}}"
    group: "{{file_group_log_dir}}"
  when: (ansible_os_family == 'FreeBSD')
  tags:
    - install
    - nginx

- name: 'file create vhosts.d'
  file:
    state: 'directory'
    path: "{{file_dst_vhosts_d}}"
    mode: "{{file_mode_vhosts_d}}"
    owner: "{{file_owner_vhosts_d}}"
    group: "{{file_group_vhosts_d}}"
  tags:
    - install
    - nginx

- name: 'stat file dhparam.pem'
  stat:
    path: "{{file_dst_dhparam_pem}}"
  register: register_dhparam_pem
  tags:
    - install
    - nginx

- name: 'stat file monit.d'
  stat:
    path: "{{file_dst_monit_d}}"
  register: register_monit_d
  when: (nginx_monitor_monit_state is match('true|yes|enable'))
  tags:
    - install
    - nginx

- name: 'file create monit.d'
  file:
    state: 'directory'
    path: "{{file_dst_monit_d}}"
    mode: "{{file_mode_monit_d}}"
    owner: "{{file_owner_monit_d}}"
    group: "{{file_group_monit_d}}"
  when: (nginx_monitor_monit_state is match('true|yes|enable')) and (register_monit_d.stat.exists == False)
  tags:
    - install
    - nginx

#-------------------------------------------------------------------------------
# COMMANDS
#-------------------------------------------------------------------------------

- name: 'command generate dhparam'
  shell: "{{command_cmd_generate_dhparam}}"
  check_mode: 'no'
  when: (register_dhparam_pem.stat.exists == False)
  tags:
    - install
    - nginx

- name: 'command check service monit'
  shell: "{{command_cmd_check_service_monit}}"
  register: register_check_service_monit
  changed_when: (register_check_service_monit.rc > 1)
  failed_when: (register_check_service_monit.rc > 1)
  check_mode: 'no'
  when: (nginx_monitor_monit_state is match('true|yes|enable'))
  tags:
    - install
    - nginx
