---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'
  tags:
    - disable
    - tinc

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'file create tinc.cfg'
  template:
    src: "{{file_src_tinc_cfg}}"
    dest: "{{file_dst_tinc_cfg}}"
    mode: "{{file_mode_tinc_cfg}}"
    owner: "{{file_owner_tinc_cfg}}"
    group: "{{file_group_tinc_cfg}}"
  notify: 'service reload monit'
  when: (tinc_monitor_monit_state is match('true|yes|enable'))
  tags:
    - disable
    - tinc

#-------------------------------------------------------------------------------
# COMMANDS
#-------------------------------------------------------------------------------

- name: 'command status tinc'
  command: "{{command_cmd_status_tinc}}"
  register: register_status_tinc
  changed_when: (register_status_tinc.rc > 1)
  failed_when: (register_status_tinc.rc > 1)
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD')
  tags:
    - disable
    - tinc

- name: 'command disable tinc'
  command: "{{command_cmd_disable_tinc}}"
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD') and (register_status_tinc.rc == 0)
  tags:
    - disable
    - tinc

- name: 'command check tinc'
  command: "{{command_cmd_check_tinc}}"
  register: register_check_tinc
  changed_when: (register_check_tinc.rc > 1)
  failed_when: (register_check_tinc.rc > 1)
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD')
  tags:
    - disable
    - tinc

- name: 'command stop tinc'
  command: "{{command_cmd_stop_tinc}}"
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD') and (register_check_tinc.rc == 0)
  tags:
    - disable
    - tinc
