---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
      - "vars/{{ansible_os_family}}.yml"
      - 'vars/main.yml'
      skip: 'true'
  tags:
    - install
    - vim

#-------------------------------------------------------------------------------
# PACKAGING
#-------------------------------------------------------------------------------

- name: 'package install vim'
  package:
    state: 'present'
    name: "{{package_name_vim}}"
  tags:
    - install
    - vim

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'file create vimrc'
  template:
    src: "{{file_src_vimrc}}"
    dest: "{{file_dst_vimrc}}"
    mode: "{{file_mode_vimrc}}"
    owner: "{{file_owner_vimrc}}"
    group: "{{file_group_vimrc}}"
  tags:
    - install
    - vim
