---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
      - "vars/{{ansible_os_family}}.yml"
      - 'vars/main.yml'
      skip: 'true'
  tags:
    - remove
    - main
    - bash

#-------------------------------------------------------------------------------
# PACKAGING
#-------------------------------------------------------------------------------

- name: 'package remove bash'
  package:
    state: 'absent'
    name: "{{package_name_bash}}"
  tags:
    - remove
    - main
    - bash

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'file remove bash.bash'
  file:
    state: 'absent'
    path: "{{file_path_bash_bash}}"
  tags:
    - remove
    - main
    - bash

- name: 'file remove zz_bash.bash'
  file:
    state: 'absent'
    path: "{{file_path_zz_bash_bash}}"
  tags:
    - remove
    - main
    - bash
