---

- name: import tasks install
  import_tasks: install.yml
  when: not (coreutils_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - coreutils

- name: import tasks remove
  import_tasks: remove.yml
  when: (coreutils_state is match('false|no|remove'))
  tags:
    - coreutils
