---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
      - "vars/{{ansible_os_family}}.yml"
      - 'vars/main.yml'
      skip: 'true'
  tags:
    - install
    - common

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'file create common-app.dir'
  file:
    state: 'directory'
    path: "{{file_dst_common_app_dir}}"
    mode: "{{file_mode_common_app_dir}}"
    owner: "{{file_owner_common_app_dir}}"
    group: "{{file_group_common_app_dir}}"
  tags:
    - install
    - common

- name: 'file create common-backup.dir'
  file:
    state: 'directory'
    path: "{{file_dst_common_backup_dir}}"
    mode: "{{file_mode_common_backup_dir}}"
    owner: "{{file_owner_common_backup_dir}}"
    group: "{{file_group_common_backup_dir}}"
  tags:
    - install
    - common

- name: 'file create common-data.dir'
  file:
    state: 'directory'
    path: "{{file_dst_common_data_dir}}"
    mode: "{{file_mode_common_data_dir}}"
    owner: "{{file_owner_common_data_dir}}"
    group: "{{file_group_common_data_dir}}"
  tags:
    - install
    - common

- name: 'file create common-script.dir'
  file:
    state: 'directory'
    path: "{{file_dst_common_script_dir}}"
    mode: "{{file_mode_common_script_dir}}"
    owner: "{{file_owner_common_script_dir}}"
    group: "{{file_group_common_script_dir}}"
  tags:
    - install
    - common

- name: 'file create README'
  template:
    src: "{{file_src_readme}}"
    dest: "{{file_dst_readme}}"
    mode: "{{file_mode_readme}}"
    owner: "{{file_owner_readme}}"
    group: "{{file_group_readme}}"
  tags:
    - install
    - common
