---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
      - "vars/{{ansible_os_family}}.yml"
      - 'vars/main.yml'
      skip: 'true'
  tags:
    - remove
    - unix
    - root

#-------------------------------------------------------------------------------
# SYSTEM
#-------------------------------------------------------------------------------

- name: 'authorized_key remove root'
  authorized_key:
    state: 'absent'
    user: "{{authorized_key_user_root}}"
    key: "{{'' if (root_authorized_key|match('false|no|remove')) else root_authorized_key}}"
    key_options: "{{'' if (root_authorized_key_options|match('false|no|remove')) else root_authorized_key_options}}"
  tags:
    - system
    - remove
    - unix
    - root
