---

- name: import tasks main
  import_tasks: main/main.yml
  when: ((ansible_os_family == 'FreeBSD') and (ansible_distribution_release is match("12\.2-*"))) or ((ansible_os_family == 'OpenBSD') and (ansible_distribution_version == '7.0'))
  tags:
    - ldns
