---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'

#-------------------------------------------------------------------------------
# COMMANDS
#-------------------------------------------------------------------------------

- name: 'command smtpctl aliases'
  command: "{{command_cmd_smtpctl_aliases}}"

#-------------------------------------------------------------------------------
# SYSTEM
#-------------------------------------------------------------------------------

- name: 'service start opensmtpd'
  service:
    state: 'started'
    name: "{{service_name_opensmtpd}}"

- name: 'service restart opensmtpd'
  service:
    state: 'restarted'
    name: "{{service_name_opensmtpd}}"
