---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'
  tags:
    - disable
    - openssh

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'file create banner'
  template:
    src: "{{file_src_banner}}"
    dest: "{{file_dst_banner}}"
    mode: "{{file_mode_banner}}"
    owner: "{{file_owner_banner}}"
    group: "{{file_group_banner}}"
  tags:
    - disable
    - openssh

- name: 'file create moduli'
  template:
    src: "{{file_src_moduli}}"
    dest: "{{file_dst_moduli}}"
    mode: "{{file_mode_moduli}}"
    owner: "{{file_owner_moduli}}"
    group: "{{file_group_moduli}}"
  tags:
    - disable
    - openssh

- name: 'file create ssh_config'
  template:
    src: "{{file_src_ssh_config}}"
    dest: "{{file_dst_ssh_config}}"
    mode: "{{file_mode_ssh_config}}"
    owner: "{{file_owner_ssh_config}}"
    group: "{{file_group_ssh_config}}"
  tags:
    - disable
    - openssh

- name: 'file create sshd_config'
  template:
    src: "{{file_src_sshd_config}}"
    dest: "{{file_dst_sshd_config}}"
    mode: "{{file_mode_sshd_config}}"
    owner: "{{file_owner_sshd_config}}"
    group: "{{file_group_sshd_config}}"
  tags:
    - disable
    - openssh

- name: 'line disable sshd_enable'
  lineinfile:
    state: 'present'
    line: "{{file_line_sshd_enable}}=\"NO\" # Ansible: Disable openssh"
    regexp: "^{{file_line_sshd_enable}}="
    dest: "{{file_dst_sshd_enable}}"
    create: 'yes'
  when: (ansible_os_family == 'FreeBSD')
  tags:
    - disable
    - openssh

#-------------------------------------------------------------------------------
# COMMANDS
#-------------------------------------------------------------------------------

- name: 'command status openssh'
  command: "{{command_cmd_status_openssh}}"
  register: register_status_openssh
  changed_when: (register_status_openssh.rc > 1)
  failed_when: (register_status_openssh.rc > 1)
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD')
  tags:
    - disable
    - openssh

- name: 'command disable openssh'
  command: "{{command_cmd_disable_openssh}}"
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD') and (register_status_openssh.rc == 0)
  tags:
    - disable
    - openssh

- name: 'command check openssh'
  command: "{{command_cmd_check_openssh}}"
  register: register_check_openssh
  changed_when: (register_check_openssh.rc > 1)
  failed_when: (register_check_openssh.rc > 1)
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD')
  tags:
    - disable
    - openssh

- name: 'command stop openssh'
  command: "{{command_cmd_stop_openssh}}"
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD') and (register_check_openssh.rc == 0)
  tags:
    - disable
    - openssh

#-------------------------------------------------------------------------------
# SYSTEM
#-------------------------------------------------------------------------------

- name: 'service stop openssh'
  service:
    state: 'stopped'
    enabled: 'no'
    name: "{{service_name_openssh}}"
  when: (ansible_os_family == 'FreeBSD')
  tags:
    - disable
    - openssh
