---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'
  tags:
    - install
    - node_exporter

#-------------------------------------------------------------------------------
# PACKAGING
#-------------------------------------------------------------------------------

- name: 'package install node_exporter'
  package:
    state: 'present'
    name: "{{package_name_node_exporter}}"
  tags:
    - install
    - node_exporter

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'file create data.dir'
  file:
    state: 'directory'
    path: "{{file_dst_data_dir}}"
    mode: "{{file_mode_data_dir}}"
    owner: "{{file_owner_data_dir}}"
    group: "{{file_group_data_dir}}"
  tags:
    - install
    - node_exporter

- name: 'file create node_exporter_data.dir'
  file:
    state: 'directory'
    path: "{{file_dst_node_exporter_data_dir}}"
    mode: "{{file_mode_node_exporter_data_dir}}"
    owner: "{{file_owner_node_exporter_data_dir}}"
    group: "{{file_group_node_exporter_data_dir}}"
  tags:
    - install
    - node_exporter

- name: 'file create textfile_collector.dir'
  file:
    state: 'directory'
    path: "{{file_dst_textfile_collector_dir}}"
    mode: "{{file_mode_textfile_collector_dir}}"
    owner: "{{file_owner_textfile_collector_dir}}"
    group: "{{file_group_textfile_collector_dir}}"
  tags:
    - install
    - node_exporter

- name: 'line config node_exporter_textfile_dir'
  lineinfile:
    state: 'present'
    line: "{{file_line_node_exporter_textfile_dir}}"
    regexp: "^{{file_regexp_node_exporter_textfile_dir}}=.*"
    dest: "{{file_dest_node_exporter_textfile_dir}}"
    create: 'yes'
  when: (ansible_os_family == 'FreeBSD')
  tags:
    - install
    - node_exporter

- name: 'line config node_exporter_flags'
  lineinfile:
    state: 'present'
    line: "{{file_line_node_exporter_flags}}"
    regexp: "^{{file_regexp_node_exporter_flags}}=.*"
    dest: "{{file_dest_node_exporter_flags}}"
    create: 'yes'
  when: (ansible_os_family == 'OpenBSD')
  tags:
    - install
    - node_exporter
