---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
      - "vars/{{ansible_os_family}}.yml"
      - 'vars/main.yml'
      errors: 'ignore'
  tags:
    - remove
    - shell

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'file remove shell.sh'
  file:
    state: 'absent'
    path: "{{file_dst_shell_shell}}"
  tags:
    - remove
    - shell

- name: 'file remove z_shell.sh'
  file:
    state: 'absent'
    path: "{{file_dst_z_shell_shell}}"
  tags:
    - remove
    - shell
