---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
      - "vars/{{ansible_os_family}}.yml"
      - 'vars/main.yml'
      skip: 'true'
  tags:
    - config
    - sudo

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'template create sudo-config'
  template:
    src: "{{file_src_sudo_config}}"
    dest: "{{file_path_sudoers_d}}/{{item.order if (item.order is defined) else ''}}{{'-' if (item.order is defined) else ''}}{{item.name if (item.name is defined) and not (item.name == '') else sudo_name_default}}"
    mode: "{{file_mode_sudo_config}}"
    owner: "{{file_owner_sudo_config}}"
    group: "{{file_group_sudo_config}}"
    validate: "{{file_validate_sudo_config}}"
  with_items: "{{sudo_all + sudo_dependencies + sudo_group + sudo_host}}"
  when: not (item.state is match('false|no|remove'))
  tags:
    - config
    - sudo

- name: 'file remove sudo-config'
  file:
    state: 'absent'
    path: "{{file_path_sudoers_d}}/{{item.order if (item.order is defined) else ''}}{{'-' if (item.order is defined) else ''}}{{item.name if (item.name is defined) and not (item.name == '') else sudo_name_default}}"
  with_items: "{{sudo_all + sudo_dependencies + sudo_group + sudo_host}}"
  when: (item.state is match('false|no|remove'))
  tags:
    - config
    - sudo
