---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
      - "vars/{{ansible_os_family}}.yml"
      - 'vars/main.yml'
      skip: 'true'
  tags:
    - install
    - sudo

#-------------------------------------------------------------------------------
# PACKAGING
#-------------------------------------------------------------------------------

- name: 'package install sudo'
  package:
    state: 'present'
    name: "{{package_name_sudo}}"
  tags:
    - install
    - sudo

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'file create sudoers.d'
  file:
    state: 'directory'
    path: "{{file_dst_sudoers_d}}"
    mode: "{{file_mode_sudoers_d}}"
    owner: "{{file_owner_sudoers_d}}"
    group: "{{file_group_sudoers_d}}"
  tags:
    - install
    - sudo

- name: 'template create sudoers'
  template:
    src: "{{file_src_sudoers}}"
    dest: "{{file_dst_sudoers}}"
    mode: "{{file_mode_sudoers}}"
    owner: "{{file_owner_sudoers}}"
    group: "{{file_group_sudoers}}"
    validate: "{{file_validate_sudoers}}"
  tags:
    - install
    - sudo
