---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'
  tags:
    - remove
    - ntpd

#-------------------------------------------------------------------------------
# COMMANDS
#-------------------------------------------------------------------------------

- name: 'command info ntpd'
  shell: "{{command_cmd_info_ntpd}}"
  register: register_info_ntpd
  failed_when: (register_info_ntpd.rc > 1)
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD')
  tags:
    - remove
    - ntpd

- name: 'command disable ntpd'
  command: "{{command_cmd_disable_ntpd}}"
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD') and (register_info_ntpd.rc == 0)
  tags:
    - remove
    - ntpd

- name: 'command stop ntpd'
  command: "{{command_cmd_stop_ntpd}}"
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD') and (register_info_ntpd.rc == 0)
  tags:
    - remove
    - ntpd

#-------------------------------------------------------------------------------
# PACKAGING
#-------------------------------------------------------------------------------

- name: 'package remove ntpd'
  package:
    state: 'absent'
    name: "{{package_name_ntpd}}"
  register: register_freebsd_ntpd
  tags:
    - remove
    - ntpd

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'line remove ntpd_enable'
  lineinfile:
    state: 'absent'
    line: "{{file_line_ntpd_enable}}=\"NO\" # Ansible: Remove ntpd"
    regexp: "^{{file_line_ntpd_enable}}="
    dest: "{{file_dst_ntpd_enable}}"
    create: 'yes'
  when: (ansible_os_family == 'FreeBSD')
  tags:
    - remove
    - ntpd

- name: 'cron remove ntpd_check-time'
  cron:
    state: 'absent'
    name: "{{cron_name_ntpd_check_time}}"
    user: "{{cron_user_ntpd_check_time}}"
  tags:
    - remove
    - ntpd

- name: 'file remove ntpd_check-time'
  file:
    state: 'absent'
    path: "{{file_dst_ntpd_check_time}}"
  tags:
    - remove
    - ntpd

- name: 'cron remove ntpd_update-time'
  cron:
    state: 'absent'
    name: "{{cron_name_ntpd_update_time}}"
    user: "{{cron_user_ntpd_update_time}}"
  tags:
    - remove
    - ntpd

- name: 'file remove ntpd_update-time'
  file:
    state: 'absent'
    path: "{{file_dst_ntpd_update_time}}"
  tags:
    - remove
    - ntpd

- name: 'file remove ntp.conf'
  file:
    state: 'absent'
    path: "{{file_dst_ntp_conf}}"
  tags:
    - remove
    - ntpd
