---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'
  tags:
    - enable
    - postfix

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'file create aliases'
  template:
    src: "{{file_src_aliases}}"
    dest: "{{file_dst_aliases}}"
    mode: "{{file_mode_aliases}}"
    owner: "{{file_owner_aliases}}"
    group: "{{file_group_aliases}}"
  notify:
    - 'command newaliases'
    - 'service restart postfix'
  tags:
    - enable
    - postfix

- name: 'file create main.cf'
  template:
    src: "{{file_src_main_cf}}"
    dest: "{{file_dst_main_cf}}"
    mode: "{{file_mode_main_cf}}"
    owner: "{{file_owner_main_cf}}"
    group: "{{file_group_main_cf}}"
  notify: 'service restart postfix'
  tags:
    - enable
    - postfix

- name: 'file create master.cf'
  template:
    src: "{{file_src_master_cf}}"
    dest: "{{file_dst_master_cf}}"
    mode: "{{file_mode_master_cf}}"
    owner: "{{file_owner_master_cf}}"
    group: "{{file_group_master_cf}}"
  notify: 'service restart postfix'
  tags:
    - enable
    - postfix

- name: 'line enable postfix_enable'
  lineinfile:
    state: 'present'
    line: "{{file_line_postfix_enable}}=\"YES\" # Ansible: Enable postfix"
    regexp: "^{{file_line_postfix_enable}}="
    dest: "{{file_dst_postfix_enable}}"
    create: 'yes'
  when: (ansible_os_family == 'FreeBSD')
  tags:
    - enable
    - postfix

#-------------------------------------------------------------------------------
# SYSTEM
#-------------------------------------------------------------------------------

- name: 'service start postfix'
  service:
    state: 'started'
    enabled: 'yes'
    name: "{{service_name_postfix}}"
  when: (ansible_os_family == 'FreeBSD')
  tags:
    - enable
    - postfix
