---

- name: import tasks install
  import_tasks: install.yml
  when: not (icmpinfo_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - icmpinfo

- name: import tasks remove
  import_tasks: remove.yml
  when: (icmpinfo_state is match('false|no|remove'))
  tags:
    - icmpinfo
