---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
      - "vars/{{ansible_os_family}}.yml"
      - 'vars/main.yml'
      errors: 'ignore'
  tags:
    - config
    - nsd

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'file create config'
  template:
    src: "{{file_src_config}}"
    dest: "{{file_dst_config}}/{{item.name}}.zone"
    mode: "{{file_mode_config}}"
    owner: "{{file_owner_config}}"
    group: "{{file_group_config}}"
  with_items: "{{nsd_zone}}"
  notify:
    - 'command nsd-checkconf'
    - 'service restart nsd'
  when: not (item.state|default('true') is match('false|no|remove'))
  tags:
    - config
    - nsd

- name: 'file remove config'
  file:
    state: 'absent'
    path: "{{file_dst_config}}/{{item.name}}.zone"
  with_items: "{{nsd_zone}}"
  notify:
    - 'command nsd-checkconf'
    - 'service restart nsd'
  when: (item.state|default('true') is match('false|no|remove'))
  tags:
    - config
    - nsd
