---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'
  tags:
    - enable
    - nsd

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'command locate unbound'
  command: "{{command_cmd_locate_unbound}}"
  register: register_locate_unbound
  changed_when: (register_locate_unbound.rc > 1)
  failed_when: (register_locate_unbound.rc > 1)
  check_mode: 'no'
  tags:
    - enable
    - nsd

- name: 'file create nsd.conf'
  template:
    src: "{{file_src_nsd_conf}}"
    dest: "{{file_dst_nsd_conf}}"
    mode: "{{file_mode_nsd_conf}}"
    owner: "{{file_owner_nsd_conf}}"
    group: "{{file_group_nsd_conf}}"
    validate: "{{file_validate_nsd_conf}}"
  notify: 'service restart nsd'
  when: (register_locate_unbound.rc == 1)
  tags:
    - enable
    - nsd

- name: 'file create nsd.conf'
  template:
    src: "{{file_src_nsd_conf}}"
    dest: "{{file_dst_nsd_conf}}"
    mode: "{{file_mode_nsd_conf}}"
    owner: "{{file_owner_nsd_conf}}"
    group: "{{file_group_nsd_conf}}"
    validate: "{{file_validate_nsd_conf}}"
  notify:
    - 'service restart nsd'
    - 'service restart unbound'
  when: (register_locate_unbound.rc == 0)
  tags:
    - enable
    - nsd

- name: 'line enable nsd_enable'
  lineinfile:
    state: 'present'
    line: "{{file_line_nsd_enable}}=\"YES\" # Ansible: Enable nsd"
    regexp: "^{{file_line_nsd_enable}}="
    dest: "{{file_dst_nsd_enable}}"
    create: 'yes'
  when: (ansible_os_family == 'FreeBSD')
  tags:
    - enable
    - nsd

#-------------------------------------------------------------------------------
# COMMANDS
#-------------------------------------------------------------------------------

- name: 'command status nsd'
  command: "{{command_cmd_status_nsd}}"
  register: register_status_nsd
  changed_when: (register_status_nsd.rc > 1)
  failed_when: (register_status_nsd.rc > 1)
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD')
  tags:
    - enable
    - nsd

- name: 'command enable nsd'
  command: "{{command_cmd_enable_nsd}}"
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD') and (register_status_nsd.rc == 1)
  tags:
    - enable
    - nsd

- name: 'command check nsd'
  command: "{{command_cmd_check_nsd}}"
  register: register_check_nsd
  changed_when: (register_check_nsd.rc > 1)
  failed_when: (register_check_nsd.rc > 1)
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD')
  tags:
    - enable
    - nsd

- name: 'command start nsd'
  command: "{{command_cmd_start_nsd}}"
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD') and (register_check_nsd.rc == 1)
  tags:
    - enable
    - nsd

#-------------------------------------------------------------------------------
# SYSTEM
#-------------------------------------------------------------------------------

- name: 'service start nsd'
  service:
    state: 'started'
    enabled: 'yes'
    name: "{{service_name_nsd}}"
  when: (ansible_os_family == 'FreeBSD')
  tags:
    - enable
    - nsd
