---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'
  tags:
    - enable
    - rest_server

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'file create rest_server.service'
  template:
    src: "{{file_src_rest_server_service}}"
    dest: "{{file_dst_rest_server_service}}"
    mode: "{{file_mode_rest_server_service}}"
    owner: "{{file_owner_rest_server_service}}"
    group: "{{file_group_rest_server_service}}"
  notify: 'service restart rest_server'
  tags:
    - enable
    - rest_server

- name: 'file create rest_server.cfg'
  template:
    src: "{{file_src_rest_server_cfg}}"
    dest: "{{file_dst_rest_server_cfg}}"
    mode: "{{file_mode_rest_server_cfg}}"
    owner: "{{file_owner_rest_server_cfg}}"
    group: "{{file_group_rest_server_cfg}}"
  notify: 'service reload monit'
  when: (rest_server_monitor_monit_state is match('true|yes|enable'))
  tags:
    - enable
    - rest_server

#-------------------------------------------------------------------------------
# COMMANDS
#-------------------------------------------------------------------------------

- name: 'command status rest_server'
  command: "{{command_cmd_status_rest_server}}"
  register: register_status_rest_server
  changed_when: (register_status_rest_server.rc > 1)
  failed_when: (register_status_rest_server.rc > 1)
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD')
  tags:
    - enable
    - rest_server

- name: 'command enable rest_server'
  command: "{{command_cmd_enable_rest_server}}"
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD') and (register_status_rest_server.rc == 1)
  tags:
    - enable
    - rest_server

- name: 'command check rest_server'
  command: "{{command_cmd_check_rest_server}}"
  register: register_check_rest_server
  changed_when: (register_check_rest_server.rc > 1)
  failed_when: (register_check_rest_server.rc > 1)
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD')
  tags:
    - enable
    - rest_server

- name: 'command start rest_server'
  command: "{{command_cmd_start_rest_server}}"
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD') and (register_check_rest_server.rc == 1)
  tags:
    - enable
    - rest_server

#-------------------------------------------------------------------------------
# SYSTEM
#-------------------------------------------------------------------------------

- name: 'service start rest_server'
  service:
    state: 'started'
    enabled: 'yes'
    name: "{{service_name_rest_server}}"
  tags:
    - enable
    - rest_server
